### ISSUE TITLE
Add Saving/Downloading Functionality

### ISSUE THREAD

**Issue by campbeln** [ZLightning/elasticsearch-head#1]
"Structured Query" will get a "Save Results As..." button, probably based on the following code snippit - https://stackoverflow.com/a/28464611/235704

"Any Request"

NOTE: this looks to be the checkbox at the top of the Structured Query page
4:27 https://github.com/ZLightning/elasticsearch-head/blob/master/_site/app.js#L4059

**Comment by campbeln** [comment]
Just because I'm sure I've missed something:

Garfield
1:33 I got some hopefully quick and easy requests for enhancing a tool we use called elasticsearch-head
ngnick
2:42 cool, how can I help?
Garfield
2:48 Hi :)
ngnick
2:48 I just accepted the invite
Garfield
2:48 I don't know much about jquery
ngnick
2:49 I've got ya covered there :)
Garfield
2:49 So I was hoping you could figure out how to add a save button and/or a copy to clipboard button
ngnick
2:49 can do
2:49 the copy to clipboard is less simple, but I have it workin in Zonecruncher so it should be a near copy/paste
Garfield
2:49 elasticsearch-head is a great help, but it has some features that appear to be just missing
ngnick
2:50 how would we "save"? Throw data at an API url?
Garfield
2:51 The data is loaded into a UI, so I am assuming there is a way to send the string to a file, but maybe it is just wishful thinking.
2:52 This is the right file: https://github.com/ZLightning/elasticsearch-head/blob/master/_site/app.js
2:53 I found what I had to fix to make it find the base fields I have long wanted to be able to search from the pull down, and I fixed that code already.
ngnick
2:54 Well, we can send it to "local storage" but that's browser based, so login on a different machine, outta luck
Garfield
2:55 elasticsearch-head is browser based
2:55 Do you mean that localStorage saves to a cookie?
ngnick
2:56 I know that, but if we save to the server in some way/shape/form than we can persist based on user, while some other solutions (cookies, localstorage) are based on a particular browser install
2:56 conceptually, yes, localstorage and cookies have the same limitations
Garfield
2:57 I am thinking the second answer here might be what I was looking for: https://stackoverflow.com/questions/28464449/save-json-data-locally-on-the-machine
2:58 Ideally we would also have a pretty print check box
ngnick
2:59 huh, I'll have to try that top answer, never seen that before but in theory that should work
2:59 pretty print… I'll have to look into that but yea should be able to
3:00 can I load this site anywhere?
Garfield
3:02 I could set it up somewhere for you, let me see where would be a good playground...
ngnick
3:02 cool, that'll help!
Garfield
3:18 Trying to throw up a quick temp cluster, but it seems to be fighting me :(
3:20 permissions issue, I fixed it
3:20 Now I just have to open up some access from outside
3:21 BTW, this is not a super high priority task.  If you have something more pressing, these enhancements can wait
Garfield
3:38 Is this still a good IP for you 207.231.94.198?
AprilDL
3:41 ngnick
ngnick
3:47 yep, tha'ts my IP
AprilDL
3:48 you have our vpn tho right?
ngnick
3:48 I do, so that can also work!
Garfield
3:57 I opened up the access... the only problem is that it doesn't like the http protocol...
ngnick
3:58 https ok?
Garfield
3:59 http://54.163.249.48:9100/es/_plugin/head/
3:59 I just had to not use the host name
4:00 Now I just have to index some data so we have something to play with.
ngnick
4:00 cool, that loaded up just fine
4:01 so where do we need the save/download/etc button?
4:01 (that is, can I get a use case)
Garfield
4:06 Ok, we got some data :)
ngnick
4:07 sweet
4:07 so what's the process I will go thru that ends with the new functionality
4:07 ?
Garfield
4:07 On the tab that reads structured query
4:07 And there is another that would be nice too... the tab that reads any request
4:08 The structured query tab is the one that we tend to use whenever possible, the any request tab is more of an advanced search
4:09 Curious... is jquery slow?
ngnick
4:09 ok, so Structured Query, after submit and getting results we'd have a "download" button
Garfield
4:09 Sure, download makes sense.
ngnick
4:09 no, jQuery was the first attempt to standardize Javascript programming
4:09 it's a bit shit on now as "it
4:09 's old"
4:09 but it's a nice tech that without we'd not be doing half the stuff with JS that we're doing now
Garfield
4:11 From stackoverflow page we looked at earlier, I think it is the saveText function in the second answer that seems to be the closest to what I think we want for a save button.
4:11 https://stackoverflow.com/questions/28464449/save-json-data-locally-on-the-machine
ngnick
4:12 this one?
4:12 https://stackoverflow.com/a/28464611/235704
Garfield
4:12 I think the first answer states exactly what you said before I posted that link, that the localStorage function would not "download" the file
4:12 Yes
ngnick
4:12 agh, funny, as that one linked above is my first while the local storage one is second (hence my confusion)
Garfield
4:13 Ah, weird, it sorts opposite for me :)
ngnick
4:13 that looks like a cool way to do the download, so I'm happy to play with it as it's a sneaky way to get the job done :)
Garfield
4:13 :)
ngnick
4:14 ok, so Structured Query will get a "Download" button (or we could call it "Save As…" or whatever)
4:14 now, what about Any Request?
Garfield
4:17 My best guess as to where the code would be for this is in this range: https://github.com/ZLightning/elasticsearch-head/blob/master/_site/app.js#L870-L1072
4:18 Perhaps we should make the button "Save Results As..." or something
ngnick
4:18 ok, can do
Garfield
4:18 that way we know we are not trying to save the query
ngnick
4:18 love the dearth of comments :)
Garfield
4:20 BTW for pretty printing JSON, it is just a matter of calling JSON.stringify(objToPrettyPrint, null, '\t')
4:20 \t is for a single tab
ngnick
4:20 agh, cool!
Garfield
4:20 a number represents spaces per level
4:21 I mean in place of '\t' a number is spaces
4:25 Hmmmm, I think I may have linked you to the wrong section...
ngnick
4:26 I'm a bit surprised how it's structured…
4:26 I'm digging through the code now to try and get my bearings
4:27 this looks to be the checkbox at the top of the Structured Query page
4:27 https://github.com/ZLightning/elasticsearch-head/blob/master/_site/app.js#L4059
Garfield
4:27 Yes, I do believe it is
4:28 I thought I was linking you to the section I was working on earlier, but I accidentally linked you to something that contained a string I used to find that section :)
ngnick
4:29 heh, global search for strings, that's how I'm finding stuff too :P
4:29 stupid internationalized labels!
4:33 Just to capture our discussion https://github.com/ZLightning/elasticsearch-head/issues/1
Garfield
4:33 I added a crontab to pull every minute, so you should be able to see changes you deploy after a minute
ngnick
4:33 (feel free to edit!)

**Comment by ZLightning** [comment]
If we can get the save button to work, then we should be able to add the option (check box) for pretty printing.  That changes `JSON.stringify(obj)` to `JSON.stringify(obj, null, prettyPrint)` where `prettyPrint` could be a number, string, or undefined.  A number represents number of spaces per level, where a string is multiplied by the nested level in the JSON (so '\t' would be 1 tab per level).

**Comment by campbeln** [comment]
With some fighting, it looks like the "Structured Query" portion is working!

**Comment by campbeln** [comment]
Huh, well... I totally did THAT on purpose! Looks like Any Request is working now too!

We could refactor the code a wee bit me thinks but there's no nice global object I can see to attach to outside of `window`.

**Comment by ZLightning** [comment]
Works as expected for JSON Structured Query and Any Request.  The table has an odd structure to the JSON, but is still good enough for now.  I don't think we can spend any more time on this now.
